### PR TITLE
Feature: Support codeship docker environment variables

### PR DESCRIPTION
**Pull request by mrcrgl**
Hi @nickmerwin 

Codeship has published its new Docker implementation with some helpful environment variables. I think many people who're using docker will be glad to remove the .git files from the container.

[https://codeship.com/documentation/docker/steps/#build-environment](Codeship Docker configuration)

Marc

### CODE REVIEW

**Comment by mrcrgl** [comment]
Hi @nickmerwin,

would you please have a look at my change? The failing doesn't seem to belong to my change `The command "make test-coveralls" exited with 2.` (missing repo token). 

- Marc

**Comment by ash14** [comment]
Is there an update on this? I'm seeing "Unknown Commit Message" for all builds, so I'd like to have this PR merged in as well.

**Comment by mrcrgl** [comment]
@nickmerwin would you please have a look at this PR?

**Comment by nickmerwin** [comment]
Thank you @mrcrgl!

**Pull request merged**
