### PR TITLE
Add buildkite support

### PR DESCRIPTION
**Pull request by tjdavey**
- Adds support for reporting from Buildkite build agents - Documentation for environment variables is available here: https://buildkite.com/docs/builds/environment-variables

### CODE REVIEW

**Comment by tjdavey** [comment]
@nickmerwin I've had a go at reproducing the failing test on my local environment but can't reproduce or see a clear reason why it is failing. Is this a known Travis issue?

**Comment by tjdavey** [comment]
There is a race condition in the tests resulting in the test failure of this PR. This race condition is resolved by #179. When merged this should resolve the failing tests in this PR.

**Comment by hartror** [comment]
Any blockers on getting this merged I could help with?

**Comment by nickmerwin** [comment]
Thanks @tjdavey !

**Pull request merged**
