### PR TITLE
Remove cobertura-parse (reverts #243)

### PR DESCRIPTION
**Pull request by XhmikosR**
cobertura-parse is archived and in bad shape. They even have mocha in dependencies.

See also [my comment](https://github.com/nickmerwin/node-coveralls/pull/243#issuecomment-556948457)

### CODE REVIEW

**Comment by ly-cultureiq** [comment]
mocha is only used for tests it seems - not for actual code. so it should just go into devdependencies. otherwise the cobertura spec hasnt changed it seems - so the code works perfectly fine

**Comment by XhmikosR** [comment]
You are missing the point. cobertura-parse has mocha in its dependencies, thus everyone who depends on it has to download and install the useless mocha dep.

**Comment by XhmikosR** [comment]
Or to put it better: everyone who depends on cobertura-parse, **downloads and installs** the useless mocha dependency inadvertently.

**Comment by nickmerwin** [comment]
@ly-cultureiq apologies for the back and forth, I didn't realize the state of the https://github.com/vokal/cobertura-parse package. If there was an actively maintained alternative I'd be happy to bring it back in, but for now I'd prefer not to have this package depend on an archived one.

**Comment by nickmerwin** [comment]
@XhmikosR thank you for the rebase!

**Comment by ly-cultureiq** [comment]
@nickmerwin no problems - im now noticing https://github.com/coverage-report/cobertura-json - which seems to be more maintained and should be a drop in replacement - Im happy to make a pr based of that if you and @XhmikosR think that would work

**Comment by XhmikosR** [comment]
That seems better but keep in mind https://packagephobia.now.sh/result?p=%40cvrg-report%2Fcobertura-json

**Comment by ly-cultureiq** [comment]
i saw that - its all direct dependencies of xml2js - so theres not really a way around that install size...

**Comment by XhmikosR** [comment]
It's @nickmerwin to decide. xml2js could be improved in the future but the main issue here IMHO is that https://github.com/coverage-report/cobertura-json is a fork.

**Pull request merged**
