### PR TITLE
WIP Replace request with teeny-request

### LINKED ISSUE #204: Replace `request` lib?
Request is really bloated, and since it seems to only be used here to make a simple POST request, we can easily replace it with something lighter like got or axios. See https://bundlephobia.com/result?p=request@2.88.0

### PR DESCRIPTION
**Pull request by XhmikosR**
Draft because I could use some help with tests

@nickmerwin if you have any suggestions how to fix the tests to stub `teeny-request` since it doesn't expose a `post` function let me know 🙂

[Size comparison](https://packagephobia.now.sh/result?p=request%2Cteeny-request):

Screenshot_2020-05-03 Package Phobia

This is an alternative to #275 with a package that has very close API to request. I'm not sure if v6.0.3 works with Node.js 6.x, but we'll know for sure after we fix the tests.

If merged fixes #204 and closes #275.

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
https://www.npmjs.com/package/axios could also be a good replacement

**Comment by XhmikosR** [comment]
I'm trying to keep using callbacks and not promises.

**Comment by mykola-mokhnach** [comment]
> I'm trying to keep using callbacks and not promises.

Any particular reason for that? I thought everything is now moving to promises for good

**Comment by XhmikosR** [comment]
The whole codebase is using callbacks, I'm not going to change that myself 😛

**Pull request closed without merging**
