### PR TITLE
If COVERALLS_SERVICE_NUMBER is set, set service_number from it.

### PR DESCRIPTION
**Pull request by midgleyc**
Coveralls allows to set separately a service_number and job_id, but only the job_id was currently being set. This adds the option to use an environment variable to set a different service_number if desired.

I've also removed the duplicate service_pull_request set on the json.

### CODE REVIEW

**Comment by phated** [comment]
This should either use `service_job_number` or change those references to `service_number` because that option isn't being serialized currently.

Also, I'd love to see this patch landed.

**Comment by midgleyc** [comment]
Wouldn't it be better to serialize job number, if it can be specified using a separate environment variable?

Admittedly, I worked on this so long ago I don't recall how the service works any more.

**Comment by nickmerwin** [comment]
Hi @midgleyc could you supply an example setup on a CI where the explicit setting of that environment variable is necessary?

**Comment by midgleyc** [comment]
If I recall correctly, it was an Azure DevOps release pipeline.

**Comment by joscha** [comment]
can we get this one in, please?

**Comment by nickmerwin** [comment]
Hi @midgleyc would you be up for resolving the conflicts when you get a chance, please?

**Comment by midgleyc** [comment]
Sure, I think I've resolved it.

Bit of a blast from the past here, thanks for looking at it!

**Comment by nickmerwin** [comment]
Thank you @midgleyc! Releasing now.

**Pull request merged**
