### PR TITLE
tests: fix deprecation warning and update sinon to 8.x

### PR DESCRIPTION
**Pull request by XhmikosR**
@nickmerwin BTW it seems there's also a `createSandbox` function but it seems we just need the default one. Let me know if you think we should switch to `createSandbox()`.

See https://sinonjs.org/releases/v8.1.1/sandbox/#default-sandbox

### CODE REVIEW

**Comment by XhmikosR** [comment]
The failing test seems unrelated to these changes; restarting CI should fix the issue.

**Comment by XhmikosR** [comment]
@nickmerwin friendly ping for this PR and the other 2 ones 🙂

BTW please ping me to rebase any of my PRs, if needed.

**Comment by nickmerwin** [comment]
Hey @XhmikosR, CI is green now, could you solve the conflict and rebase, please?

**Comment by XhmikosR** [comment]
Done!

**Comment by nickmerwin** [comment]
Thanks @XhmikosR!

**Pull request merged**
