### PR TITLE
Use HEAD to pick up git info

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
This is mostly explained in https://github.com/nickmerwin/node-coveralls/issues/80, the commit pointed to by TRAVIS_COMMIT may, or in my experience likely wont exist in the tree and cannot be `cat-file`d, so using HEAD is better in that case. I am not a git expert so happy to do a better way if there is one

**Comment by nickmerwin** [comment]
Hi @daleharvey, thanks for the PR! I'm wondering why we shouldn't use `HEAD` to get info for all CI's, not just Travis. Can you see any reason against that?

**Comment by daleharvey** [comment]
So the downside of this is the HEAD commit in travis on pull requests does not contain the commit message last used, it will look like `Merge 8a6e4faae457974eae9258776a9bb7d4bf745b86 into 963175fa273ae0a214b4ee4f49282ea49922a9d2` I was kinda hoping this PR might prompt someone who knows git + travis better than I to have a better solution. 

One possible one is to handle the failure of `git cat-file` and just use HEAD at that point, the message wont be great but it will work at least

**Comment by nickmerwin** [comment]
@daleharvey ok I'm merging this to fix the exception. Will wait on further discussion regarding the commit message not being as descriptive as it could in this contingency.

**Comment by Saulis** [comment]
@daleharvey @nickmerwin as coveralls.io seems to look for the source files for the builds using the given commit, using `HEAD` effectively makes every build run in Travis in any other branch than the default branch use invalid / missing source files.

**Comment by nickmerwin** [comment]
@Saulis could you link me to an example of this?

**Comment by Saulis** [comment]
@nickmerwin sure:

I ran a Travis build using the latest version of `coveralls` in a branch called `latest-coveralls` :
https://travis-ci.org/vaadin/vaadin-grid/builds/160368379 (see log line 2073).

That resulted in: https://coveralls.io/builds/7915973 – notice the "HEAD on github" link on top left corner. If you try to click on any of the files in the coverage listing, you'll get an "SOURCE NOT AVAILABLE" error on most of them, since those files are not present in the `master` branch of our repo. Only the `vaadin-grid.html` happens to be on `master`, but that's a totally different version from what is in the `latest-coveralls` branch.

––––

Here's another build that has been run on `2.0-dev` branch which uses `2.11.3` version of `coveralls`: https://travis-ci.org/vaadin/vaadin-grid/builds/159400839

Here's the coveralls build: https://coveralls.io/builds/7850485

As you can see, the top left link now says correctly "3D52C559 on github" and all the source files work.

Thanks for looking into this!

**Pull request merged**
